### ISSUE TITLE
Some files need to be updated first. Specify --force to overwrite remote files.

### ISSUE THREAD

**Issue by r4mkum4r** [tomalec/Sublime-Text-2-Vlt-Plugin#2]
I keep getting this error when I commit.

**Comment by tomalec** [comment]
Thanks for feedback. That usually happens, when your file was updated on CQ after last update/checkout.
(vlt does not check file-system against CQ repo, but file-system against its local `.vlt` file, which may be out of sync)
Have you tried call `vtl: Update` (ctrl+shift+p commmand) before commit (save). If update fails as well, could you give its output?

**Comment by r4mkum4r** [comment]
I didn't try UPDATE. Will update the result here.

**Comment by tomalec** [comment]
But, please be aware that `vlt: update` may overwrite your changes with CQ version, so make copy, or at least keep it it open to `ctrl+z` ;)
